version: '3'
services:
  billing-service:
    build: billing_service
    volumes:
      - ./billing_service:/app/billing_service
      - ./common:/app/common
      - logvolume01:/var/log
    links:
      - event-store
      - message-queue
  crm-service:
    build: crm_service
    volumes:
      - ./crm_service:/app/crm_service
      - ./common:/app/common
      - logvolume01:/var/log
    links:
      - event-store
      - message-queue
  customer-service:
    build: customer_service
    volumes:
      - ./customer_service:/app/customer_service
      - ./common:/app/common
      - logvolume01:/var/log
    links:
      - event-store
      - message-queue
  gateway-api:
    build: gateway_api
    ports:
      - "5000:5000"
    volumes:
      - ./gateway_api:/app/gateway_api
      - ./common:/app/common
      - logvolume01:/var/log
    links:
      - event-store
      - message-queue
  inventory-service:
    build: inventory_service
    volumes:
      - ./inventory_service:/app/inventory_service
      - ./common:/app/common
      - logvolume01:/var/log
    links:
      - event-store
      - message-queue
  messaging-service:
    build: messaging_service
    volumes:
      - ./messaging_service:/app/messaging_service
      - ./common:/app/common
      - logvolume01:/var/log
    links:
      - message-queue
  order-service:
    build: order_service
    volumes:
      - ./order_service:/app/order_service
      - ./common:/app/common
      - logvolume01:/var/log
    links:
      - event-store
      - message-queue
  product-service:
    build: product_service
    volumes:
      - ./product_service:/app/product_service
      - ./common:/app/common
      - logvolume01:/var/log
    links:
      - event-store
      - message-queue
  event-store:
    build: event_store
    volumes:
      - logvolume01:/var/log
    links:
      - redis
  message-queue:
    build: message_queue
    volumes:
      - logvolume01:/var/log
    links:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  logvolume01: {}
