version: '3'
services:
  billing-service:
    build: billing_service
    volumes:
      - .:/app
      - logvolume01:/var/log
    links:
      - event-store
  crm-service:
    build: crm_service
    volumes:
      - .:/app
      - logvolume01:/var/log
    links:
      - event-store
  customer-service:
    build: customer_service
    volumes:
      - .:/app
      - logvolume01:/var/log
    links:
      - event-store
  gateway-api:
    build: gateway_api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - logvolume01:/var/log
    links:
      - event-store
  inventory-service:
    build: inventory_service
    volumes:
      - .:/app
      - logvolume01:/var/log
    links:
      - event-store
  msg-service:
    build: msg_service
    volumes:
      - .:/app
      - logvolume01:/var/log
  order-service:
    build: order_service
    volumes:
      - .:/app
      - logvolume01:/var/log
    links:
      - event-store
  product-service:
    build: product_service
    volumes:
      - .:/app
      - logvolume01:/var/log
    links:
      - event-store
  event-store:
    build: event_store
    volumes:
      - .:/app
      - logvolume01:/var/log
    links:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  logvolume01: {}
